server:
  port: 5051

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: "postgres"
    password: "password"
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
